### ISSUE TITLE
Computation Time for Each Image

### ISSUE THREAD

**Issue by Yiming-M** [weizheliu/Context-Aware-Crowd-Counting#3]
Hi Weizhe and Zhaoyi,

First of all I'd like to show my gratitude for your great contribution in image crowd counting. Your work may have benefited numerous other researchers (including me).

I am very interested in extending your work CAN to real-time video crowd counting, in which computation time really matters. Could you upload your trained models to this repo or do you have any idea about how much time it took to process one image from those benchmark datasets?

Many thanks,
Yiming

**Comment by weizheliu** [comment]
Thank you for your interest in our work.

If you are interested in the computation time for our model, you could refer to one recent [paper](https://arxiv.org/pdf/2003.10120.pdf), which compares the computation of several crowd counting models at Table 1.

Hope this solves your problem.

**Comment by weizheliu** [comment]
I would assume the "thumb up" react means the problem already solved, if you have more questions, please feel free to open the the issue again :)

**Comment by Yiming-M** [comment]
Hi Weizhe,

Sorry for this much delayed reply.

I have found the info I need in your recent paper _Efficient Crowd Counting via Structured Knowledge Transfer_, and thanks a lot for your help.

Wish you a productive & nice week!

Many thanks,
Yiming
