### ISSUE TITLE
Shrunk Output Size

### ISSUE THREAD

**Issue by Yiming-M** [weizheliu/Context-Aware-Crowd-Counting#4]
Hi Weizhe,

In your code, there is max pooling with stride and kernel size of 2 in the encoder, but there is no corresponding treatment to enlarge the layer output in the decoder. As a result, the final output size will be smaller, which means the density map does not have the same height and width of the input image.

Best wishes,
Yiming

**Comment by weizheliu** [comment]
Yes, the output density map is down-sampled by a factor of 8, you could enlarge the output by transposed conv layer if you want. But it may take more parameters and does not bring any improvement in performance, so I just keep it like this.

**Comment by Yiming-M** [comment]
Hi Weizhe,

Thanks for you reply. I added some upsampling layers to ensure the density map and the original image have the same width & height.

Many thanks,
Yiming
