### ISSUE TITLE
how can i generates the heat map in this code

### ISSUE THREAD

**Issue by ssa567832** [weizheliu/Context-Aware-Crowd-Counting#5]
please tell me how can i generates the heat map in this code,thank you very much

**Comment by weizheliu** [comment]
You could use the script 'make_dataset.py' to generate the heat map.

**Comment by ssa567832** [comment]
Thank you for your answer.Is it can be visualized in photo?  btw have a nice day

**Comment by weizheliu** [comment]
Yes, you could check this [code](https://github.com/weizheliu/People-Flows/blob/main/plot.py) as example of how to visualize the density map. Hope this solves your problem.

**Comment by ssa567832** [comment]
I will try it.Thank you very much.

**Comment by weizheliu** [comment]
Please feel free to re-open it if this does not solve your problem.
