### ISSUE TITLE
Thank you for providing us with technical assistance.  We tried to plot the density using `https://github.com/weizheliu/People-Flows/blob/main/plot.py` file on this directory  " context aware crowd counting"  but it gives an error of importing CANNet2s. Since we trained the CANNet model defined in model.py file.  We are interested in plot density maps only using the CANNet not using the CANNet2s. Then, is it still possible to generate density maps using CANNet model ?

### ISSUE THREAD

**Issue by aliraza0769** [weizheliu/Context-Aware-Crowd-Counting#6]
Thank you for providing us with technical assistance.  We tried to plot the density using `https://github.com/weizheliu/People-Flows/blob/main/plot.py` file on this directory  " context aware crowd counting"  but it gives an error of importing CANNet2s. Since we trained the CANNet model defined in model.py file.  We are interested in plot density maps only using the CANNet not using the CANNet2s. Then, is it still possible to generate density maps using CANNet model ?

_Originally posted by @aliraza0769 in https://github.com/weizheliu/Context-Aware-Crowd-Counting/issues/2#issuecomment-963857888_

**Comment by weizheliu** [comment]
Sure, you only need to change CANNet2s to CANNet and for CANNet2s there are 10 channels in the output and I plot each channel respectively. For CANNet, there is only one output channel, you could directly use the same plot function.
